package vn.lochv.demosdkandroid

data class NfcModel(
    var sessionId: String? = null,
    var type: String? = null,
    var number: String? = null,
    var name: String? = null,
    var firstName: String? = null,
    var lastName: String? = null,
    var dob: String? = null,
    var sex: String? = null,
    var nationality: String? = null,
    var doe: String? = null,
    var mrz: String? = null,
    var file: String? = null,
    var aaSignature: String? = null,
    var aaPublicKey: String? = null,
    var keyAlg: String? = null,
    var imgLiveNess: String? = null,
    var faceMatching: String? = null,
    var isFaceMatching: Boolean? = null,
    var sodData: String? = null,
    var dg1DataB64: String? = null,
    var dg2DataB64: String? = null,
    var dg13DataB64: String? = null,
    var dg14DataB64: String? = null,
    var fileId: String? = null,
    var bodyFileId: String? = null,
    var numberVMN: String? = null,
    var nameVNM: String? = null,
    var dobVMN: String? = null,
    var sexVMN: String? = null,
    var nationalityVMN: String? = null,
    var nationVNM: String? = null,
    var religionVMN: String? = null,
    var homeTownVMN: String? = null,
    var residentVMN: String? = null,
    var identificationSignsVNM: String? = null,
    var registrationDateVMN: String? = null,
    var doeVMN: String? = null,
    var nameDadVMN: String? = null,
    var nameMomVMN: String? = null,
    var otherPaper: String? = null,
    var nameCouple: String? = null,
    var raw: String? = null,
    var phone: String? = null,
    var isView: Boolean = false,
    var statusSuccess: Boolean = false,
    var visibleButtonDetail: Boolean = true,
    var kind: String? = null
) {

}
